modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Dungeons/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons"
logoFile="logo.png"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
credits="${modCredits}"
authors="${modAuthor}"
description="${modDescription}"

[[dependencies.betterdungeons]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="SERVER"

[[dependencies.betterdungeons]]
modId="yungsapi"
versionRange="[1.16.4-Forge-6,)"
mandatory=true
ordering="NONE"
side="BOTH"
